name: Windows VM Docker

on:
  workflow_dispatch:

jobs:
  vm:
    name: Start Windows VM
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Prepare Docker
        run: |
          sudo apt update

          sudo systemctl start docker || true

          docker --version
          docker compose version || docker-compose --version

      - name: Download Windows VM config
        run: |
          mkdir -p dockercomp
          cd dockercomp

          wget -O Win10VLqL.yml \
          https://raw.githubusercontent.com/VLqL069/Win10/7a57fa82a99c1cf3cfaeed17a629d0856061692e/Win10VLqL.yml

          ls -la

      - name: Start Windows VM
        run: |
          cd dockercomp

          if command -v docker-compose; then
            sudo docker-compose -f Win10VLqL.yml up
          else
            sudo docker compose -f Win10VLqL.yml up
          fi
