name: Windows VM Docker + Bore

on:
  workflow_dispatch:

jobs:
  vm:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - uses: actions/checkout@v4

      - name: Atualizar pacotes
        run: |
          sudo apt update
          sudo apt install -y wget curl

      - name: Verificar Docker
        run: |
          docker --version
          docker compose version

      - name: Baixar configuração da VM
        run: |
          mkdir -p dockercomp
          cd dockercomp
          wget -O Win10VLqL.yml \
          https://raw.githubusercontent.com/VLqL069/Win10/7a57fa82a99c1cf3cfaeed17a629d0856061692e/Win10VLqL.yml

      - name: Instalar Bore
        run: |
          wget -O bore.tar.gz https://github.com/ekzhang/bore/releases/latest/download/bore-v0.5.2-x86_64-unknown-linux-musl.tar.gz
          tar -xzf bore.tar.gz
          chmod +x bore
          sudo mv bore /usr/local/bin/

      - name: Iniciar Bore
        run: |
          bore local 3389 --to bore.pub &

      - name: Iniciar VM Windows
        run: |
          cd dockercomp
          docker compose -f Win10VLqL.yml up
